### ISSUE TITLE
React native - crashes with wrong data.

### ISSUE THREAD

**Issue by dasoga** [hps/heartland-example-code#18]
Hi

I'm trying to implement the library in react native, I used the SDK for iOS, works well in the happy path.
Do you know why is crashing if I put info card like "1234567890123456" (wrong data)
This is my code in  **HeartlandTokenizer.m**

```

#import <Heartland-iOS-SDK/HpsTokenService.h>

#import "HeartlandTokenizer.h"

@implementation HeartlandTokenizer

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(tokenize:(NSString *)cardNumber
                  cardExpiration:(NSString *)cardExpiration
                  cardCvv:(NSString *)cardCvv
                  callback:(RCTResponseSenderBlock)callback)
{
  @try {
    HpsTokenService *service = [[HpsTokenService alloc] initWithPublicKey:@"myKey"];

    NSArray *expParts = [cardExpiration componentsSeparatedByString:@" / "];

    if ([expParts count] != 2) {
      callback(@[@"invalid date", [NSObject init]]);
      return;
    }

    [service getTokenWithCardNumber:cardNumber
                                cvc:cardCvv
                           expMonth:expParts[0]
                            expYear:expParts[1]
                   andResponseBlock:^(HpsTokenData *tokenResponse) {

                     callback(@[[NSNull null], @{
                                  @"token_value": tokenResponse.tokenValue
                     }]);
                     
                   }];
  } @catch (NSException *exception) {
    callback(@[exception.reason, [NSObject init]]);
  }
};

@end

```
Thanks!

**Comment by slogsdon** [comment]
Hi @dasoga! You're more than likely seeing an error response object being passed to your response block that isn't being handled correctly since there will be no token value available in this case. Here's a small example from our tests where [an error response is being expected](https://github.com/hps/heartland-ios/blob/master/Example/Tests/Heartland_TokenizationTests.m#L89-L94). Let us know if that doesn't resolve your issue.

**Comment by dasoga** [comment]
Well, it looks like that's the problem.
I'm using the same code that you have [here in react-native example](https://github.com/hps/heartland-example-code/blob/master/javascript/react-native/ios/HeartlandRNExample/HeartlandTokenizer.m)

Actually your example it's crashing too
I'll try to fix the code and let you know...thanks for response!
